### ISSUE TITLE
Integrate Noosphere Name System with CLI gateway

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#109]
As of #93 and the resolution of #67, we will have the bones of a name system capable of publishing names to and resolving names from a DHT.

Once these pieces are in place, we should integrate the "name system" as a worker thread that is managed by the gateway process (as implemented by the `orb` CLI). The gateway will spin up the name system thread and share access to local sphere data with it. The name system thread will read from sphere "address books." Address books should probably be in the form of a `VersionedMap<String, String>` where the key is an arbitrary string and the value is a DID. In our examples, we call this field on the sphere "names," but that's not set in stone. Names in address books will be queued for periodic resolution by querying the DHT.

Additionally, there should be a way for the main gateway process to notify the name system thread that it should publish a new version of a given sphere to the DHT.

**Comment by cdata** [comment]
I'm putting in some of the data structure work for this via #153

**Comment by jsantell** [comment]
As of #253 and related work, this is broadly completed and tracked in remaining issues.
