### ISSUE TITLE
Rename `noosphere` crate to `noosphere-core`

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#110]
The name of the `noosphere` crate is a bit misleading: it sounds like it is the entrypoint for someone who is interested in the collective body of code, but in fact it is just the kernel of our code base (mostly just the raw IPLD type definitions as associated implementation). We should rename the crate to `noosphere-core` to more appropriately reflect its purpose.

**Comment by TomLisankie** [comment]
This issue is done, right? https://crates.io/crates/noosphere-core

**Comment by jsantell** [comment]
> This issue is done, right? https://crates.io/crates/noosphere-core

yes! thanks for catching this, fixed via #112
