### ISSUE TITLE
Pet name system

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#12]
Our plan at this time is to implement a generalized pet name system that enables users to write human-readable names instead of DIDs when addressing other spheres.

This is the tracking issue that covers progress towards our pet name system.

## Design notes

The proposed design for this system expects the following:

 - Every Sphere has an associated ed25519 key pair
 - Every Sphere revision can be referred to by a CID
 - A field in the Sphere maps human-readable names to DIDs (probably via a HAMT)
 - A DHT from which the CID of the latest revision of a Sphere can be resolved if the Sphere's public key is known

Spheres already have a key pair generated for them when they are first created. Spheres are already immutable data structures and can be looked up by CID.

The notion of a Sphere is sufficiently developed to encode a name-to-DID mapping, but the field needs to be added and incorporated with our versioning scheme. And, we have yet to implement a DHT.

## Errata

In our prototyping phase, we implemented a global, recursive name system using a CosmWasm smart contract. This was an interesting design, but ultimately we decided that a block chain is ill-suited to tracking mutable pointers. A single change could cost multiple pennies (denominated in USD), and recursive name resolution compounds the cost at each "hop" (where a hop is another contract invocation in this case). If every revision to a Sphere - where each individual revision could amount to a very small change - prompted a change to the pointer in the block chain, the cost to publish adds up quickly.

**Comment by gordonbrander** [comment]
I think this may be done?
