### ISSUE TITLE
Implement an error passing / handling strategy for FFI

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#145]
Maybe more discussion needed here, but how do we generally translate fallible Rust calls over FFI? For this method, we could return the number of written bytes so there's a programmatic way of observing runtime failures -- e.g. maybe this method isn't actually writing to disk, where a "reasonable failure" could occur, but could be represented as a `bool` return value. I think it's common for C libs to have at the very least booleans on every fallible method (or an int enum with `NsOK` or `NsFailure` or something) due to lack of catching. Creation methods can return `NULL` on failed calls indicating failure (documented as such).

Not suggesting this at the moment but illustrating possibilities, to have a more robust error mechanism, e.g. `NsResponse` on every method call with `NsFailure => 0, NsOk => 1, NsFsWriteError = 2` and so forth, we'd also need method calls taking addresses to allocate into, which would be a larger change:
```c
NsSphereFs* sphere_fs;
if (NsOk != ns_sphere_fs_open(&sphere_fs)) {
  // handle error, `sphere_fs` is NULL
}
```

_Originally posted by @jsantell in https://github.com/subconsciousnetwork/noosphere/pull/141#discussion_r1021848846_

**Comment by cdata** [comment]
One thought I had was to implement some kind of global error handler that could be registered with `NoosphereContext`. Another option would be to implement some kind of ad-hoc `Result` type to be used in FFI.

**Comment by jsantell** [comment]
out-errors have since been implemented in the FFI -- closing!
