### ISSUE TITLE
Vend a `wasm32-unknown-unknown` artifact with TypeScript bindings based on `noosphere`

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#164]
Now that we have a viable high-level API in the form of `noosphere` via #123 , we should enable a build path to create a `wasm32-unknown-unknown` library artifact with corresponding TypeScript bindings. There are a few paths to accomplishing this, but perhaps the easiest one is to add a [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen)-based FFI. Then, we can add the artifact generation to our automatic build pipeline and include the artifacts with releases of `noosphere`.

**Comment by kinostl** [comment]
Sorry for the simple question, I'm new to rust. Would the idea with this be to decorate the crate with wasm-bindgen and export?

**Comment by cdata** [comment]
Sort of. We'll add some FFI-specific constructs similar to what we added for #131 (see sources under `ffi`). Those will be decorated with `wasm-bindgen` macros for generating a Wasm API.

**Comment by cdata** [comment]
This is actually done as of #165
