### ISSUE TITLE
Introduce an NPM package built around Noosphere Wasm library

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#165]
As a follow-up to #164 and in the spirit of #131 , we should introduce an NPM package (that is, a JavaScript package built from TypeScript sources) that wraps the Noosphere Wasm library (and associated TypeScript bindings) in a high-level API that is suitable for general consumption by web developers who are comfortable wielding the NPM package ecosystem.

The package should probably load and run the Wasm core in a web worker, while the high-level API may be wielded from the main thread or another worker.

**Comment by kinostl** [comment]
Would this allow web browsers to host clients for Noosphere, or would it be focused on node.js?

**Comment by cdata** [comment]
@kinostl this is primarily intended for web browsers, actually. Node.js is an interesting use-case, but I can't guarantee that we will support it out of the box right away.
