### ISSUE TITLE
Investigate avoiding manual drop calls when using TempDir

### ISSUE THREAD

**Issue by jsantell** [subconsciousnetwork/noosphere#166]
In #162 and the NS bootstrap, we use the TempDir crate, with the former manually calling `drop()` to cleanup temp dirs, and the latter not doing so results in dangling dirs in `/tmp/`. Investigate to see why the TempDir requires manual dropping

**Comment by cdata** [comment]
I think we have determined that we don't need to manually drop, and have stopped doing it as of #171
