### ISSUE TITLE
`noosphere` tests are flakey

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#167]
Build where it failed mysteriously: https://github.com/subconsciousnetwork/noosphere/actions/runs/3498576071/jobs/5859116116

Summary of failure:

```
---- sphere::builder::tests::it_can_create_a_sphere_and_later_open_it stdout ----
thread 'sphere::builder::tests::it_can_create_a_sphere_and_later_open_it' panicked at 'called `Result::unwrap()` on an `Err` value: IO error: could not acquire lock on "/tmp/t2ec9-4/.sphere/storage/db": Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', rust/noosphere/src/sphere/builder.rs:371:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cdata** [comment]
Looks like maybe all of `noosphere` tests are haunted: https://github.com/subconsciousnetwork/noosphere/actions/runs/3498686886/jobs/5859368904

This very likely traces back to #162 :(

**Comment by cdata** [comment]
These flakes are few and far between, but I'm sad to say we are still seeing them: https://github.com/subconsciousnetwork/noosphere/actions/runs/3567939081/jobs/5996231905

**Comment by cdata** [comment]
Another flake: https://github.com/subconsciousnetwork/noosphere/actions/runs/3662928873/jobs/6192360285

**Comment by cdata** [comment]
The same flake strikes again, but this time in `noosphere-cli`: https://github.com/subconsciousnetwork/noosphere/actions/runs/4077987629/jobs/7027661126

I wonder if `sled` is racing itself... maybe we can make sure it flushes before our storage is dropped?

**Comment by jsantell** [comment]
Closing in favor of tracking IO lock errors in #579 (as none of the logs here are still around)
