### ISSUE TITLE
Improve storage abstraction to allow for specialized blockstore

### ISSUE THREAD

**Issue by Frando** [subconsciousnetwork/noosphere#174]
Hi,
here's a proposal that we briefly discussed on Discord today.

Currently, most of the codebase is generic over `S: Store`. The `Store` trait abstracts over key-value stores that take `key: &[u8], value: &[u8]`.  This makes it impossible to use an external block store with the frequently used `SphereDB` abstraction, because it is only generic over the `Store` and uses it for all stores, including the block store.

Instead, I propose to make the `SphereDB` and other parts of the code base generic over a `Storage` trait with associated types for (at least) a `KvStore` and a `BlockStore`. This allows implementers to use different storage backends for these stores.

In the future, more stores like the link store or the metadata could be specialized through further associated types on `Storage`.

The trait could look like this:

```rust
pub trait Storage {
    type BlockStore: BlockStore;
    type KvStore: KvStore;
    async fn get_kv_store(&self, name: &str) -> Result<Self::KvStore>;
    async fn get_block_store(&self, name: &str) -> Result<Self::BlockStore>;
}
```
As the `StorageProvider`  trait would then be used a lot to constrain generics, maybe it makes sense to rename it to just `Storage`.

The `SphereDb` could then be defined as follows:
```rust
pub struct SphereDb<S>
where
    S: Storage,
{
    block_store: S::BlockStore,
    link_store: S::KvStore,
    version_store: S::KvStore,
    metadata_store: S::KvStore,
}

````
The existing `Store` trait would be renamed to `KvStore`.

**Comment by cdata** [comment]
Thanks for filing this! This is a great observation about the limitations of how we have factored storage. Sadly, this kind of change will be rather cross-cutting, but better that we make it now rather than later.
