### ISSUE TITLE
Create FFI for getting first value for header key

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/noosphere#201]
We currently do not expose any FFI function for getting the first value for a given header key. We have something like this in Rust and JS, would be useful to expose to FFI as well.

Context: https://github.com/subconsciousnetwork/subconscious/pull/389#discussion_r1069813766.

**Comment by cdata** [comment]
Originally filed in #199, but we can take these instead.

**Comment by gordonbrander** [comment]
Fixed by https://github.com/subconsciousnetwork/noosphere/pull/202/files#diff-1efb4c78223a5de922b225414cce89a317e9cddec9c7fecb0e5c9bc177fe8acaR248
