### ISSUE TITLE
Update to `libipld` v0.16.x

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#208]
It's that time again. `libipld` has released another major revision, which means the ecosystem we depend on will probably be updating shortly. The main change is described here: https://github.com/ipld/libipld/pull/174

We need to update more-or-less in step with other crates like `wnfs` that also depend on this crate.

**Comment by matheus23** [comment]
Yeah. I just hit this after trying to use rs-wnfs v0.1.20 with noosphere-car.
I could help out with this after IPFS Thing :)

**Comment by matheus23** [comment]
This can be closed now I think

**Comment by jsantell** [comment]
Thanks @matheus23!
