### ISSUE TITLE
Ensure that name records are the most up to date during adoption

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#258]
As of #253 , we will have end-to-end name publishing and resolving. However, we don't currently verify that a given record that we are adopting is the most up to date record we have adopted for a given entry in our address book. This verification can (and probably should) be done by comparing the lifetime constraints of the name records in question, and selecting the record with the most recent "not before" (`nbf`) value.

**Comment by jsantell** [comment]
Challenges in determining definitive hosts, and is-most-recent record in a distributed network: https://github.com/subconsciousnetwork/noosphere/issues/124
