### ISSUE TITLE
Move common dependencies up to workspace Cargo.toml

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#64]
The latest Rust release includes enhanced capabilities for Cargo workspaces. In particular, common dependencies across every crate can now be specified in the workspace's Cargo.toml and inherited by the manifest for each crate in the workspace: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table

We should probably uplift the most common dependencies (such a `anyhow`, `cid`, `async_trait` etc.). In addition to cutting down on bloat in our crate-specific manifests, it will help us to keep our dependency versions in sync across all crates in the workspace.

**Comment by igbanam** [comment]
I'm currently looking into this. The ask is for "common dependencies". After reading through the workspaces doc linked, seems to me like all dependencies can be at the workspace level. How do we feel about that?
