### ISSUE TITLE
Docs.rs build fails due to `cfg_match!` on nightly toolchain

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#667]
This might be the sign from the universe that we should be running at least one CI check on the nightly toolchain.

https://docs.rs/crate/noosphere/0.15.1/builds/930119

**Comment by cdata** [comment]
@jsantell FYI

**Comment by jsantell** [comment]
Upstream bug: https://github.com/getditto/safer_ffi/pull/191
IIRC, there's just one other lifetime change needed, in addition to the above PR, to build noosphere on nightly

**Comment by jsantell** [comment]
Fixed via https://github.com/subconsciousnetwork/noosphere/pull/690
