### ISSUE TITLE
Implement typed header parsing for `ucan` header

### ISSUE THREAD

**Issue by cdata** [subconsciousnetwork/noosphere#68]
After we integrate support for changes to `rs-ucan` landing in https://github.com/ucan-wg/rs-ucan/pull/28, we will have to contend with a new world where HTTP request headers that use UCAN-based JWT for authorization may also include auxilliary `ucan` headers (see: https://github.com/ucan-wg/ucan-as-bearer-token#2-request-headers).

We already benefit from typed header parsing for the `authorization` header. We should author an extension to the typed headers that are offered by `axum` to include something to make parsing `ucan` headers more convenient and consistent.

**Comment by blaine** [comment]
If anyone looks to pick this up, we have [almost] an implementation in fission-server that will be extracted to a generic axum extractor. Will update as we get closer. It probably makes sense to implement this as a separate crate from rs-ucan, but appreciate any thoughts on the matter!

https://github.com/ucan-wg/rs-ucan/issues/122

**Comment by jsantell** [comment]
Implemented: https://github.com/subconsciousnetwork/noosphere/blob/main/rust/noosphere-core/src/api/headers/ucan.rs
